# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a131e31e2cdb9c5357ffa25eb1b93b42f51f77d883e1358efe06d47b9c07224361c3a0958c974eab31a8a5c18868a2d56e2a69148589ab3e2245af5d4b92ac3

test:
  secret_key_base: dad9ea048116955a3dc9af4c79162fab7d88e8c4711c3fc5deeabf096d1fac8102de1bae2c24a6f131774fb77c61f514429c8508ffb7f465c0f2c63fc07ad310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
