# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cd3a2f15bc721f1bfb8c4abc6a3093387689c57c7245503936cf606b8993def829f676acf51fc4e556bb859a9c540617ec39d3a7662e7ae686dcc97492a8169

test:
  secret_key_base: 7e68a788bd8dde61887c7c4a5f04b5f56c1124aaca6ddbac55adf5f1f2acf5dbd60511821145777240cebdd76cf8cc6a050308618e6df5ed516afa96be541aef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
