# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b582414e1fcc0508a74242209d7e7cfc3b0e72c1cf947166fbabb544ac2219d32cb370f01dee305eeb516c03c521b6e6b5e998c9fde56e46508d97fd6752a21

test:
  secret_key_base: 0e03d53fd6c3be39be5b9544218344bd77fe6c87299364cc0f3296b9378f40caa89a7505aad0c4640da30383b83441c5b2da23c6f77d709b2336c01104713b3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
