# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dce9f9100fa60b90eef63f917658c8a5220124f3fe2f8098bf39d59d1d3c28642e50bd8c97573fd33b8cfd03adb7c30d8a293d8e0e51fbb99a9bbf0ee8a1d09e

test:
  secret_key_base: 922106673604a284ba4501ab387d5da76ab53aa2c22521396e919db023732d228725ffaef09d627dbdad3028db940459b8362b5c8873c2f8e2280b279ae89e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
