# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb123c9a2225bb70cd2c321593742f7a603570553901ae469526f5b651133a9e42a39cf04ec35416ae367f82ea0aea07fadf0c51b1a6278f43bd1e11d0878365

test:
  secret_key_base: 8fcb886776062493cdaf9c7ecec52da44805d3325498c7af890671ac16c9d9bdc9f09162fa68f408a183cca7a041e05e50587da246f6c929d88ba4e5c53632ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
